### ISSUE TITLE
In combination with bootstrap_package tracking is still working from first load on

### ISSUE THREAD

**Issue by zzzooorrrx** [Nostrabramus/CookieLawManagement#10]
Hi,
just tried your extension the first time and Google Analytics Tracking is implemented by bootstrap_package. From first page load on the tracking is working, no matter if I consent or not. The setting used is opt-in.
Any idea how to solve?

Regards Wolfgang

typo3 9.5.9
bootstrap_package 10.0.7
aip_cookie_law 9.5.1

**Comment by Nostrabramus** [comment]
Hi,
thanks for reporting,
we don't think the problem is related with bootstrap_pagkage,
we are working on it, we will notice you as soon as we have resolved

regards
Abramo

**Comment by Nostrabramus** [comment]
Hello,
we just released on github a new version of the extension. This version manages directly Google Analytics code.
We changed the way Google Analytics cookies are disabled because the previous mechanism was no longer compatible with Google's new API.
Now the extension adds by itself the google analytics code into the <head> tag of the page, while you only have to enter the Google ID traking and choose whether or not you want to anonymize the IP.
I hope this solution works fine for you too.
If you need to insert the google analytics code in the html the extension will not be able to override your code to prevent its installation or disable the cookies.
However consider that if you insert the code of google analitycs with the IP anonymization set to true, GA cookies are considered technical cookies and therefore it is not necessary to remove it in the absence of an explicit consent from the user.

Please tell me if I can consider this issue as closed.

regards
Abramo

**Comment by zzzooorrrx** [comment]
Hi,
thx of all, thank you for the update.
There are some points I would like to mention/discuss.
In general it's working now.

Constants:
OnOff: when setting to off I would expect that also the gtag/js code won't be rendered

GAAnonymizeIp:
If this constant is set an error occurs in the console » Uncaught SyntaxError: missing ) after argument list

You implement gtag/js as code. Is there any need to change settings in GA or adding Tags in the Google Tag Manager. I'm not familiar with the Google Tag Manager. My problem is at the moment that there is no visit transmitted into GA.

After the latest decision of the European Court the Consent of Cookies has to be implicit in the way that any checkboxes has to be empty (not prechecked). 
Is this possible to set at the moment? Or is it possible by adding a new constant?

thank you and regards
Wolfgang

**Comment by Nostrabramus** [comment]
Hi,
thanks for reporting again,
we are taking charge and we will update you when we have news

regards 
Abramo

**Comment by Nostrabramus** [comment]
> Constants:
> OnOff: when setting to off I would expect that also the gtag/js code won't be rendered

we have better documented the new constant, if you don't want gtag / js to be rendered, you must leave the GATrackingId constant empty

> GAAnonymizeIp:
> If this constant is set an error occurs in the console » Uncaught SyntaxError: missing ) after argument list

we have fixed the bug and published the new version

>You implement gtag/js as code. Is there any need to change settings in GA or adding Tags in the Google Tag Manager. I'm not familiar with the Google Tag Manager. My problem is at the moment that there is no visit transmitted into GA.

there is no need to make changes in your GA to make our plugin working, in this case it is limited to render the GA code automatically saving the integrator work of inserting the GA code in the typoscript page.headerData. In our tests everything works correctly and we correctly record the visits inside GA.

>After the latest decision of the European Court the Consent of Cookies has to be implicit in the way that any checkboxes has to be empty (not prechecked).
>Is this possible to set at the moment? Or is it possible by adding a new constant?

we agree that the European Court the Consent of Cookies requires an explicit and non-implicit acceptation of cookies. however we think that the current working is allowed, in fact the user is forced to press the "Allow cookies" button thus giving explicit consent.

regards
Abramo
